# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 191d94b83d8bb8ba19039b8e012739099ff8c5c610ac65914eaf593c8f58c2f37b9e76f32183b8e46a5211f258f2c46e30dc7200f8d553ccc229ec8336f5302e

test:
  secret_key_base: 9837099ed80638cafb51680efcc358cfd34f4b3f2cd7d96c373451c17e716c57fa9b3e3c441068cb38647028324e1db62e085d854780c1eada4f942fc8fc7c43

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
